const items = [
  {
    id: 1,
    name: "Produto A",
    price: 19.99,
    category: "Eletrônicos",
    images: [],
  },
  // {
  //   id: 2,
  //   name: "Produto B",
  //   price: 9.99,
  //   category: "Livros",
  //   images: [],
  // },
  // {
  //   id: 3,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 4,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 5,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 6,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 7,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 8,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 9,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 10,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 11,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 12,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 13,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 14,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
];

export default items;
