const items = [
  {
    id: 1,
    name: "Camiseta tradicional",
    price: "19,99",
    category: "Eletrônicos",
    images: ["https://linkss.app/uUXyv"],
  },
  {
    id: 2,
    name: "Calça jeans",
    price: "99,99",
    category: "Livros",
    images: ["https://linkss.app/UxMKO", "https://linkss.app/ZngzU"],
  },
  {
    id: 3,
    name: "Camiseta Azul",
    price: 29.99,
    category: "Roupas",
    images: ["https://linkss.app/tlOPZ"],
  },
  {
    id: 4,
    name: "Camiseta Azul",
    price: 29.99,
    category: "Roupas",
    images: ["https://linkss.app/tlOPZ"],
  },
  {
    id: 5,
    name: "Camiseta Azul",
    price: 29.99,
    category: "Roupas",
    images: ["https://linkss.app/tlOPZ"],
  },
  // {
  //   id: 4,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 5,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 6,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 7,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 8,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 9,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 10,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 11,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 12,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 13,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
  // {
  //   id: 14,
  //   name: "Produto C",
  //   price: 29.99,
  //   category: "Roupas",
  //   images: [],
  // },
];

export default items;
